### List Usuario
GET HTTP://localhost:3000/usuario

### Get Usuario
GET HTTP://localhost:3000/usuario/3

### Create Usuario
POST  HTTP://localhost:3000/usuario/

### Update Usuario
PATCH  HTTP://localhost:3000/usuario/3

### Delete Usuario
DELETE  HTTP://localhost:3000/usuario/3